from __future__ import annotations
import typing
__all__: list[str] = ['TimeNS']
class TimeNS:
    __hash__: typing.ClassVar[None] = None
    def __add__(self, arg0: TimeNS) -> TimeNS:
        ...
    def __eq__(self, arg0: TimeNS) -> bool:
        ...
    def __ge__(self, arg0: TimeNS) -> bool:
        ...
    def __gt__(self, arg0: TimeNS) -> bool:
        ...
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, ns: typing.SupportsInt) -> None:
        ...
    def __int__(self) -> int:
        ...
    def __le__(self, arg0: TimeNS) -> bool:
        ...
    def __lt__(self, arg0: TimeNS) -> bool:
        ...
    def __ne__(self, arg0: TimeNS) -> bool:
        ...
    def __repr__(self) -> str:
        ...
    def __sub__(self, arg0: TimeNS) -> TimeNS:
        ...
