#pragma once
#include <array>
#include <cassert>
#include <cstdint>
#include <cstring>
#include <memory>
#include <optional>
#include <span>
#include <string>
#include <string_view>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

#include "camera.h"
#include "commands/add_command.h"
#include "commands/connect_command.h"
#include "commands/create_group_command.h"
#include "commands/del_connection_command.h"
#include "commands/delete_comp_command.h"
#include "commands/delete_node_command.h"
#include "commands/reparent_node_command.h"
#include "commands/set_input_command.h"
#include "components/components.h"
#include "components/json_converters.h"
#include "components/non_sim_comp.h"
#include "renderer/asset_loaders.h"
#include "renderer/font.h"
#include "renderer/glyph_extractor.h"
#include "renderer/material.h"
#include "renderer/material_renderer.h"
#include "renderer/msdf_font.h"
#include "renderer/path.h"
#include "renderer/vulkan/path_renderer.h"
#include "renderer/vulkan/pipelines/circle_pipeline.h"
#include "renderer/vulkan/pipelines/grid_pipeline.h"
#include "renderer/vulkan/pipelines/path_fill_pipeline.h"
#include "renderer/vulkan/pipelines/path_stroke_pipeline.h"
#include "renderer/vulkan/pipelines/pipeline.h"
#include "renderer/vulkan/pipelines/quad_pipeline.h"
#include "renderer/vulkan/pipelines/text_pipeline.h"
#include "renderer/vulkan/text_renderer.h"
#include "scene.h"
#include "scene_serializer.h"
#include "scene_state/components/behaviours/drag_behaviour.h"
#include "scene_state/components/behaviours/mouse_behaviour.h"
#include "scene_state/components/connection_scene_component.h"
#include "scene_state/components/input_scene_component.h"
#include "scene_state/components/scene_component.h"
#include "scene_state/components/scene_component_types.h"
#include "scene_state/components/sim_scene_comp_draw_hook.h"
#include "scene_state/components/sim_scene_component.h"
#include "scene_state/components/slot_scene_component.h"
#include "scene_state/components/styles/comp_style.h"
#include "scene_state/components/styles/sim_comp_style.h"
#include "scene_state/scene_state.h"
#include "scene_ui/scene_ui.h"
#include "schematic_diagram.h"
#include "viewport.h"
