cmake_minimum_required(VERSION 3.16.0 FATAL_ERROR)

add_subdirectory(common)
add_subdirectory(bess_json)
add_subdirectory(bverilog)
add_subdirectory(bessplug/bindings)
add_subdirectory(plugin_manager)
add_subdirectory(event_system)
add_subdirectory(sim_engine)
add_subdirectory(sim_driver)
add_subdirectory(digital_sim_driver)
add_subdirectory(math_sim_driver)
add_subdirectory(project_session)
add_subdirectory(bess_core)
add_subdirectory(bess_wgpu)
add_subdirectory(ui_core)
add_subdirectory(bess)
